version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: claude-template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claude_template
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: claude-template-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Add more services as needed
  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: claude-template-mailhog
  #   restart: unless-stopped
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"

volumes:
  postgres_data:
  redis_data: